name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: [bug]
assignees: "chip-edw"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: ATTMS version
      description: What version or commit are you using?
      placeholder: e.g. v0.1.3 or commit hash
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List steps to reproduce the issue.
      placeholder: |
        1. Start the worker service
        2. Send a test email
        3. Observe error in logs
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste logs or attach images that show the issue.
      render: bash
