//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTaskTicketManager_Base.MSGraphAPI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class EmailService : global::System.Configuration.ApplicationSettingsBase {
        
        private static EmailService defaultInstance = ((EmailService)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EmailService())));
        
        public static EmailService Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("      <p class=MsoNormal><o:p>&nbsp;</o:p></p>\r\n\r\n      <p class=MsoNormal><span " +
            "lang=EN-US style=\'mso-ansi-language:EN-US\'>Dear {0},<o:p></o:p></span></p>\r\n\r\n  " +
            "    <p class=MsoNormal align=center style=\'text-align:center\'><u>{1} – {2}</u><u" +
            "><span\r\n      lang=EN-US style=\'mso-ansi-language:EN-US\'><o:p></o:p></span></u><" +
            "/p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US style=\'mso-ansi-language:EN-US\'" +
            "><o:p>&nbsp;</o:p></span></p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US style" +
            "=\'color:black;mso-ansi-language:EN-US\'>Thank\r\n      you for contacting the Flint" +
            "fox Support Team. We have logged your request for\r\n      support as Ticket {1}.&" +
            "nbsp;We will use this number to track your support request and as a\r\n      refer" +
            "ence for all communications with you. We will be in touch as we work\r\n      towa" +
            "rds a resolution for you.<o:p></o:p></span></p>\r\n\r\n      <p class=MsoNormal><spa" +
            "n lang=EN-US style=\'color:black;mso-ansi-language:EN-US\'><o:p>&nbsp;</o:p></span" +
            "></p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US style=\'color:black;mso-ansi-l" +
            "anguage:EN-US\'>By registering your ticket you\r\n      acknowledge that you are au" +
            "thorizing Flintfox to spend up to 8 hours of time\r\n      working it</span>,<span" +
            " style=\'color:black\'> noting that if it is determined to\r\n      be a defect you " +
            "will not be billed for the effort to resolve. &nbsp;If further\r\n      hours are " +
            "required we will reach out to you again seeking additional approval\r\n      by re" +
            "turn email, at which time we hope to have an estimate of the total effort\r\n     " +
            " to resolve.<o:p></o:p></span></span></p>\r\n\r\n      <p class=MsoNormal><span lang" +
            "=EN-US style=\'color:#1F497D;mso-ansi-language:\r\n      EN-US\'><o:p>&nbsp;</o:p></" +
            "span></p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US style=\'mso-ansi-language:" +
            "EN-US\'>If you have\r\n      any questions about this ticket, please reply by retur" +
            "n email or via your <a\r\n      href=\"https://ffportal.azurewebsites.net/\">Flintfo" +
            "x Portal</a>\r\n      where we will endeavor to answer your query as quickly as po" +
            "ssible. <o:p></o:p></span></p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US styl" +
            "e=\'mso-ansi-language:EN-US\'><o:p>&nbsp;</o:p></span></p>\r\n\r\n      <p class=MsoNo" +
            "rmal><span lang=EN-US style=\'mso-ansi-language:EN-US\'><o:p>&nbsp;</o:p></span></" +
            "p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US style=\'mso-ansi-language:EN-US\'>" +
            "Thank you\r\n      for your patience and support.<o:p></o:p></span></p>\r\n\r\n      <" +
            "p class=MsoNormal><span lang=EN-US style=\'mso-ansi-language:EN-US\'><o:p>&nbsp;</" +
            "o:p></span></p>\r\n\r\n      <p class=MsoNormal><span lang=EN-US style=\'mso-ansi-lan" +
            "guage:EN-US\'>Regards,<o:p></o:p></span></p>\r\n\r\n      <p class=MsoNormal><span la" +
            "ng=EN-US style=\'mso-ansi-language:EN-US\'>Flintfox\r\n      Support Team<o:p></o:p>" +
            "</span></p>\r\n\r\n      <p class=MsoNormal><span style=\'font-size:10.0pt;font-famil" +
            "y:\"Segoe UI\",sans-serif;\r\n      mso-fareast-language:EN-US\'><o:p>&nbsp;</o:p></s" +
            "pan></p>\r\n\r\n      <p class=MsoNormal><span style=\'font-size:12.0pt;font-family:\"" +
            "Times New Roman\",serif;\r\n      mso-fareast-font-family:\"Times New Roman\"\'><o:p>&" +
            "nbsp;</o:p></span></p>")]
        public string HtmlMessageText {
            get {
                return ((string)(this["HtmlMessageText"]));
            }
            set {
                this["HtmlMessageText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("    <style>\r\n      <!--a\r\n        {color:inherit;}\r\n      a:visited\r\n        {col" +
            "or:inherit;}\r\n      \r\n       /* Font Definitions */\r\n       @font-face\r\n        " +
            "{font-family:\"Cambria Math\";\r\n        panose-1:2 4 5 3 5 4 6 3 2 4;\r\n        mso" +
            "-font-charset:1;\r\n        mso-generic-font-family:roman;\r\n        mso-font-pitch" +
            ":variable;\r\n        mso-font-signature:0 0 0 0 0 0;}\r\n      @font-face\r\n        " +
            "{font-family:Calibri;\r\n        panose-1:2 15 5 2 2 2 4 3 2 4;\r\n        mso-font-" +
            "charset:0;\r\n        mso-generic-font-family:swiss;\r\n        mso-font-pitch:varia" +
            "ble;\r\n        mso-font-signature:-536859905 -1073732485 9 0 511 0;}\r\n      @font" +
            "-face\r\n        {font-family:\"Segoe UI\";\r\n        panose-1:2 11 5 2 4 2 4 2 2 3;\r" +
            "\n        mso-font-charset:0;\r\n        mso-generic-font-family:swiss;\r\n        ms" +
            "o-font-pitch:variable;\r\n        mso-font-signature:-469750017 -1073683329 9 0 51" +
            "1 0;}\r\n       /* Style Definitions */\r\n       p.MsoNormal, li.MsoNormal, div.Mso" +
            "Normal\r\n        {mso-style-unhide:no;\r\n        mso-style-qformat:yes;\r\n        m" +
            "so-style-parent:\"\";\r\n        margin:0cm;\r\n        margin-bottom:.0001pt;\r\n      " +
            "  mso-pagination:widow-orphan;\r\n        font-size:11.0pt;\r\n        font-family:\"" +
            "Calibri\",sans-serif;\r\n        mso-fareast-font-family:Calibri;\r\n        mso-fare" +
            "ast-theme-font:minor-latin;}\r\n      a:link, span.MsoHyperlink\r\n        {mso-styl" +
            "e-noshow:yes;\r\n        mso-style-priority:99;\r\n        color:#0563C1;\r\n        t" +
            "ext-decoration:underline;\r\n        text-underline:single;}\r\n      a:visited, spa" +
            "n.MsoHyperlinkFollowed\r\n        {mso-style-noshow:yes;\r\n        mso-style-priori" +
            "ty:99;\r\n        color:#954F72;\r\n        text-decoration:underline;\r\n        text" +
            "-underline:single;}\r\n      p\r\n        {mso-style-noshow:yes;\r\n        mso-style-" +
            "priority:99;\r\n        font-size:12.0pt;\r\n        font-family:\"Times New Roman\",s" +
            "erif;\r\n        mso-fareast-font-family:Calibri;\r\n        mso-fareast-theme-font:" +
            "minor-latin;}\r\n      p.msonormal0, li.msonormal0, div.msonormal0\r\n        {mso-s" +
            "tyle-name:msonormal;\r\n        mso-style-unhide:no;\r\n        mso-margin-top-alt:a" +
            "uto;\r\n        margin-right:0cm;\r\n        mso-margin-bottom-alt:auto;\r\n        ma" +
            "rgin-left:0cm;\r\n        mso-pagination:widow-orphan;\r\n        font-size:12.0pt;\r" +
            "\n        font-family:\"Times New Roman\",serif;\r\n        mso-fareast-font-family:C" +
            "alibri;\r\n        mso-fareast-theme-font:minor-latin;}\r\n      span.EmailStyle18\r\n" +
            "        {mso-style-type:personal;\r\n        mso-style-noshow:yes;\r\n        mso-st" +
            "yle-unhide:no;\r\n        font-family:\"Segoe UI\",sans-serif;\r\n        mso-ascii-fo" +
            "nt-family:\"Segoe UI\";\r\n        mso-hansi-font-family:\"Segoe UI\";\r\n        mso-bi" +
            "di-font-family:\"Segoe UI\";\r\n        color:windowtext;}\r\n      .MsoChpDefault\r\n  " +
            "      {mso-style-type:export-only;\r\n        mso-default-props:yes;\r\n        font" +
            "-size:10.0pt;\r\n        mso-ansi-font-size:10.0pt;\r\n        mso-bidi-font-size:10" +
            ".0pt;}\r\n      @page WordSection1\r\n        {size:612.0pt 792.0pt;\r\n        margin" +
            ":72.0pt 72.0pt 72.0pt 72.0pt;\r\n        mso-header-margin:36.0pt;\r\n        mso-fo" +
            "oter-margin:36.0pt;\r\n        mso-paper-source:0;}\r\n      div.WordSection1\r\n     " +
            "   {page:WordSection1;}\r\n      -->\r\n      </style>\r\n")]
        public string MessageStyleString {
            get {
                return ((string)(this["MessageStyleString"]));
            }
            set {
                this["MessageStyleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Thank you for contacting the Flintfox Support Team. 
We have logged your request for support as Ticket {1}.

We will use this number to track your support request and as a
reference for all communications with you. We will be in touch as we work
towards a resolution for you.

By registering your ticket you acknowledge that you are authorizing Flintfox to spend up to 8 hours of time
working it noting that if it is determined to
be a defect you will not be billed for the effort to resolve.

If further hours are required we will reach out to you again seeking additional approval
by return email, at which time we hope to have an estimate of the total effort
to resolve.")]
        public string TextMessage {
            get {
                return ((string)(this["TextMessage"]));
            }
            set {
                this["TextMessage"] = value;
            }
        }
    }
}
